# Generated by Django 5.2.17 on 2026-08-28 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('attending', models.BooleanField(default=True)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='core.invitation')),
            ],
            options={
                'ordering': ['-created_date'],
                'constraints': [models.UniqueConstraint(fields=('invitation', 'email'), name='uniq_rsvp_per_invitee')],
            },
        ),
    ]
