# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendingcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_hash', models.CharField(db_index=True, max_length=64)),
                ('day', models.DateField(db_index=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.invitation')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['invitation', 'day'], name='core_invita_invitat_b89b8b_idx')],
            },
        ),
    ]
