# Generated by Django 5.2.17 on 2026-08-29 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invitationview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('source', models.CharField(choices=[('built-in', 'Built-in'), ('community', 'Community')], default='community', max_length=12)),
                ('accent_color', models.CharField(blank=True, default='', max_length=16)),
                ('background_color', models.CharField(blank=True, default='', max_length=16)),
                ('cover', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source', 'name'],
            },
        ),
    ]
